apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: nsync
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage
  hostPath:
    path: "/mnt/data/rabbitmq"
