apiVersion: v1
kind: Service
metadata:
  name: user-migration-service
  namespace: nsync
spec:
  selector:
    app: user-migration-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
