apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: nsync
spec:
  replicas: 1  # Puedes cambiar el número de réplicas si es necesario
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value: "clave123"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: mipvc
