apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mipvc
  namespace: nsync
spec:
  storageClassName: bd-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
